config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', :omniauth_callbacks => 'users/omniauth_callbacks' }
  resources :quotes
  root 'quotes#index'
  
  match "*path" => redirect("/"), via: :get
  

end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :user
  validates  :content, :book, :author, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable, :omniauthable, :omniauth_providers => [:facebook]
  has_many :quotes

  def self.logins_before_captcha
    3
  end

  def self.from_omniauth(auth)
	where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	  user.email = auth.info.email
	  user.password = Devise.friendly_token[0,20]
	  #  user.name = auth.info.name   # assuming the user model has a name
	  #  user.image = auth.info.image # assuming the user model has an image
	end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use   :null_session instead.
  protect_from_forgery with: :null_session
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
  	resource.update cached_failed_attempts: 0, failed_attempts: 0
    stored_location_for(resource) || signed_in_root_path(resource)
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.where(:user_id => current_user).order(created_at: :desc)
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)
    @quote.user_id=current_user.id
    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:content, :book, :author)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
 
   
     @user = User.from_omniauth(request.env["omniauth.auth"])
     #puts "user errors: #{@user.errors.to_a}"

    if @user.persisted?
      puts "Hello"
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
     
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      
      flash.now[:alert] = "Account cannot be created with the current credentials: #{@user.email} has already been taken."
      render '/users/sessions/new'
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

 #  prepend_before_filter :must_not_be_omniauth_user, only: [:edit]


  def edit
   if user_signed_in? and not current_user.provider.blank?
   	 flash[:alert]="Editing your profile is not allowed when signed in external provider."
     redirect_to :quotes
   else
     super
    end
  end

  private
  def after_inactive_sign_up_path_for(resource)
    new_user_session_path
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def create
    flash.clear
    user = User.find_by_email(sign_in_params['email'])
    super and return unless user

    adjust_failed_attempts user

    super and return if (user.failed_attempts < User.logins_before_captcha)

    if !verify_recaptcha and recaptcha_present?(params)
      decrement_failed_attempts(user)
      self.resource = resource_class.new(sign_in_params)
      clean_up_passwords(resource)
      sign_out
      flash[:alert]="Captcha code incorrect."
      respond_with resource, location: after_sign_in_path_for(resource)
    else
      if user.access_locked?
        super and return
      else
        flash.delete :recaptcha_error
        super and return
      end
    end    
  end

 private

 def adjust_failed_attempts(user)
    if user.failed_attempts > user.cached_failed_attempts
      user.update cached_failed_attempts: user.failed_attempts
    else
      increment_failed_attempts(user)
    end
  end

  def increment_failed_attempts(user)
    user.increment :cached_failed_attempts
    user.update failed_attempts: user.cached_failed_attempts
  end

  def decrement_failed_attempts(user)
    if user.cached_failed_attempts>(User.logins_before_captcha+1)
      user.decrement :cached_failed_attempts 
      user.update failed_attempts: user.cached_failed_attempts
    end
  end


  def recaptcha_present?(params)
    if params["g-recaptcha-response"]
      return true
    else
      return false
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def errors_for(object)
	  concat(content_tag(:ul) do
	    object.errors.full_messages.each do |msg|
	      concat content_tag(:li, msg)
	    end
      end)
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

    html = <<-HTML
    <div id="alert alert-danger">
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/quotes_helper.rb
module QuotesHelper
  def created_at_format(quote)
    quote.created_at.strftime("%d %b. %Y   %H:%M")
  end
end

app/views/layouts/_active_link.html.erb
<% if current_page? path %>
  <li class="active"><%= link_to link_text, path %></li>
<% else %>
  <li><%= link_to link_text, path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookself</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Where your books meet social networking.">
  <meta name="author" content="">
  <link rel="icon" href="../../favicon.ico">
  <link href="http://fonts.googleapis.com/css?family=Lekton" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Molengo" rel="stylesheet" type="text/css">

</head>
<body>
  <nav class ="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Bookself", quotes_path, :class => "navbar-brand" %>
        </div>
        <div id="navbar" class="navbar-collapse collapse mainnav">
          <ul class="nav navbar-nav">
           <!-- <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li> -->

            <% if user_signed_in? %>
            <li><p class="navbar-text">Logged in as <strong><%= current_user.email %></strong>.</p></li>
            <% if user_signed_in? and current_user.provider.blank? %>
              <%= render :partial => "/layouts/active_link", :locals => {:path =>  edit_user_registration_path, :link_text => "Edit profile"} %>
            <% end %>
            <li> <%= link_to "Logout", destroy_user_session_path, method: :delete  %></li>
            <%if user_signed_in? and not current_user.provider.blank?  %>
              <li><%= link_to "Cancel my account",  {:controller => '/users/registrations',
              :action => 'destroy', :email => current_user.email}, data: { confirm: "Are you sure you want to cancel your account? All your data will be permanently destroyed." }, method: :delete %> </li>
            <% end %>
          <% else %>
            <%= render :partial => "/layouts/active_link", :locals => {:path =>  new_user_session_path, :link_text => "Log in"} %>
            <%= render :partial => "/layouts/active_link", :locals => {:path =>  new_user_registration_path, :link_text => "Sign up"} %>

          <% end %>

        </ul>
      </div>
    </div>
  </nav>


  <% if notice %>
    <div class="col-xs-8 col-xs-offset-2 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4 col-lg-4 col-lg-offset-4">
      <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">x</span></button>
        <%= notice %>
      </div>
    </div>
  <% end %>
  <% if alert %>
    <div class="col-xs-8 col-xs-offset-2 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4 col-lg-4 col-lg-offset-4">
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">x</span></button>
        <%= alert %>
      </div>
    </div>
  <% end %>

  <%= yield %>
  <footer>
   <div class="footer navbar-fixed-bottom">
    <p class="muted-credit">Copyright © 2015 Timea</p>
  </div>
  </footer>
</body>
</html>

app/views/quotes/_form.html.erb
<% if @quote.errors.any? %>
 <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">x</span></button>
      <ul>
      <% @quote.errors.full_messages.each do |msg| %>
        <%= content_tag :li, msg, :id => "error_#{msg}" if msg.is_a?(String) %>
      <% end %>
    </ul>
 </div>
 <% end %>
<%= form_for(@quote) do |f| %>

  <%= f.label :content, :class => "sr-only" %><br>
  <%= f.text_area :content, :class => "form-control", :placeholder => "Quote" %>
    <%= f.label :book, :class => "sr-only"  %><br>
  <%= f.text_field :book, :class => "form-control", :placeholder => "Book"  %><br />
  <%= f.label :author, :class => "sr-only"  %><br>
  <%= f.text_field :author, :class => "form-control", :placeholder => "Author"  %></br>


  <%= f.submit "Done", :class => "btn btn-warning" %>
<% end %> <br />

app/views/quotes/edit.html.erb
<main>
  <section class="container">
    <div class="col-xs-10 col-sm-6 col-md-4 col-lg-3 col-centered">
		<h1>Edit mode</h1>

		<%= render 'form' %>

		<%= button_to 'Back', quotes_path,  :class => "btn btn-default", method: :get %>
    </div>
  </section>
</main>

app/views/quotes/index.html.erb
<main>
  <section class="container">

      <div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3 col-centered">
        <h1>Quotes and stuff</h1>
        <%= button_to 'New Quote', new_quote_path, :method => :get, :class => "btn btn-primary" %> <br />
     
          <% @quotes.each do |quote| %>
           <article class="quote-box">
            <p class="form-control-static"><%= quote.content %></p>
            <p class="form-control-static"><b class="bold-tag">Book: </b><%= quote.book %></p>
            <p class="form-control-static"><b class="bold-tag">Author: </b><%= quote.author %></p>
            <p class="form-control-static">Created at: <%= created_at_format(quote) %></p>
            <!--    <%= button_to  'Show', quote_path(quote), :method => :get, :class => "btn btn-default btn-sm"  %> -->
            <%= button_to  'Edit', edit_quote_path(quote), :method => :get, :class => "btn btn-default btn-sm col-xs-offset-1 col-xs-5 col-sm-offset-1 col-sm-5 col-md-offset-2 col-md-4 col-lg-offset-2 col-lg-4", :id => "quote-button"  %>
            <%= button_to 'Delete', quote, method: :delete, data: { confirm: 'Are you sure?' },  :class => "btn btn-default btn-sm col-xs-5 col-sm-5 col-md-4  col-lg-4 quote-button " %> <br /> <br />   
           </article> 
          <% end %>
      </div>
      

  </section>
</main>
         
          

app/views/quotes/new.html.erb
<main>
  <section class="container">
    <div class="col-xs-10 col-sm-6 col-md-4 col-lg-3 col-centered">
		<h1>Write mode</h1>

		<%= render 'form' %>

		<%= button_to 'Back', quotes_path, :class => "btn btn-default", method: :get %>

    </div>
  </section>
</main>

app/views/quotes/show.html.erb
<main>
  <section class="container-show-quotes">
    <div class="col-xs-10 col-sm-6 col-md-4 col-lg-3 col-centered">
    <h1>Read mode</h1>
    <%= form_for(@quote, html: { class: "form-horizontal" }) do |f| %>
	  	  <div class="form-group">
			<%= f.label :content, "Quote: ", :class => "col-sm-4 control-label" %>
			 <div class="col-sm-8 ">
			  <p class="form-control-static"><%= @quote.content %></p><br />
			</div>
	  	  </div>
		  <div class="form-group">
		    <%= f.label :book, "Book: ", :class => "col-sm-4 control-label"  %>
		     <div class="col-sm-8 col-text-left">
			  <p class="form-control-static"><%= @quote.book %></p><br />
			</div>
		  </div>
		  <div class="form-group">
		    <%= f.label :author, "Author: ", :class => "col-sm-4 control-label" %>
		    <div class="col-sm-8 col-text-left">
			  <p class="form-control-static"><%= @quote.author %></p><br />
			</div>
		  </div>
		 <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4" id="show-quote-buttons">
		<%= button_to 'Edit', edit_quote_path(@quote), :class => "btn btn-warning", method: :get %><br />
		<%= button_to 'Back to list', quotes_path, :class => "btn btn-default", method: :get %></div><br /><br />
	<% end %>
    </div>
  </section>
</main>

app/views/users/shared/_links.html.erb
<!--Removed all, but kept the users controller structure. Check out the devise controller for the links.-->